<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260210210237 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appartement CHANGE libelle_appartement libAppart VARCHAR(255) NOT NULL, CHANGE nombre_pieces nbrePieces NUMERIC(9, 0) NOT NULL, CHANGE numero_etage numEtage INT NOT NULL, CHANGE est_occupe oqp INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contrat_location ADD dateDebut DATETIME DEFAULT NULL, ADD dateFin DATETIME DEFAULT NULL, ADD mntCaution NUMERIC(9, 0) DEFAULT NULL, ADD mntAvance NUMERIC(9, 0) DEFAULT NULL, ADD mntLoyer NUMERIC(9, 0) DEFAULT NULL, ADD autreInfos VARCHAR(255) DEFAULT NULL, ADD dateEntree DATETIME DEFAULT NULL, ADD dateProchVers DATETIME DEFAULT NULL, ADD mntLoyerPrec NUMERIC(9, 0) DEFAULT NULL, ADD mntLoyerIni NUMERIC(9, 0) DEFAULT NULL, ADD mntLoyerActu NUMERIC(9, 0) DEFAULT NULL, ADD mntArriere NUMERIC(9, 0) DEFAULT NULL, ADD dejaLocataire VARCHAR(255) DEFAULT NULL, ADD statutLoc VARCHAR(255) DEFAULT NULL, ADD totVerse VARCHAR(255) DEFAULT NULL, ADD cautionRemise NUMERIC(9, 0) DEFAULT NULL, DROP date_debut, DROP date_fin, DROP date_entree, DROP date_prochain_versement, DROP deja_locataire, DROP caution_remise, DROP montant_caution, DROP montant_avance, DROP montant_loyer, DROP autres_infos, DROP montant_loyer_precedent, DROP montant_loyer_initial, DROP montant_loyer_actuel, DROP montant_arriere, DROP statut_location, DROP total_verse, CHANGE nombre_mois_caution nbMoisCaution NUMERIC(9, 1) NOT NULL, CHANGE nombre_mois_avance nbMoisAvance NUMERIC(10, 1) DEFAULT NULL, CHANGE frais_annexes fraisAnex NUMERIC(9, 0) NOT NULL');
        $this->addSql('ALTER TABLE facture_location ADD mnt_fact INT NOT NULL, ADD solde_fact_loc INT NOT NULL, DROP montant_facture, DROP solde_facture_location, CHANGE libelle_facture lib_facture VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE locataire ADD nPrenoms VARCHAR(255) NOT NULL, ADD lieuNaiss VARCHAR(255) NOT NULL, ADD nbEnfts VARCHAR(255) DEFAULT NULL, ADD nbPersChge VARCHAR(255) DEFAULT NULL, ADD nPConjointe VARCHAR(255) DEFAULT NULL, ADD profConj VARCHAR(255) DEFAULT NULL, ADD ethnieConj VARCHAR(255) DEFAULT NULL, ADD contactConj VARCHAR(255) DEFAULT NULL, ADD vivezAvec VARCHAR(255) DEFAULT NULL, ADD numpiece VARCHAR(255) NOT NULL, DROP vivez_avec, DROP nom_prenoms, DROP lieu_naissance, DROP nombre_enfants, DROP nombre_personnes_charge, DROP nom_prenom_conjointe, DROP profession_conjointe, DROP ethnie_conjointe, DROP contact_conjointe, DROP numero_piece, CHANGE date_naissance dateNaiss DATETIME NOT NULL');
        $this->addSql('ALTER TABLE maison CHANGE libelle_maison libMaison VARCHAR(255) NOT NULL, CHANGE titre_foncier tFoncier VARCHAR(255) DEFAULT NULL, CHANGE montant_commission mntCom NUMERIC(10, 0) NOT NULL');
        $this->addSql('ALTER TABLE proprio ADD addresse VARCHAR(255) NOT NULL, ADD num_cni VARCHAR(255) NOT NULL, ADD whats_app VARCHAR(255) DEFAULT NULL, ADD lieu_naiss VARCHAR(255) NOT NULL, ADD prefession VARCHAR(255) NOT NULL, ADD nom_prenoms_r VARCHAR(255) DEFAULT NULL, ADD contacts_r VARCHAR(255) DEFAULT NULL, ADD email_r VARCHAR(255) DEFAULT NULL, ADD adresse_r VARCHAR(255) DEFAULT NULL, ADD nom_prere_r VARCHAR(255) DEFAULT NULL, ADD nom_mere_r VARCHAR(255) DEFAULT NULL, ADD whats_app_r VARCHAR(255) DEFAULT NULL, ADD date_naiss_r DATETIME DEFAULT NULL, ADD lieu_naiss_r VARCHAR(255) DEFAULT NULL, ADD profession_r VARCHAR(255) DEFAULT NULL, ADD date_cni_r DATETIME DEFAULT NULL, ADD num_cni_r VARCHAR(255) DEFAULT NULL, DROP adresse, DROP numero_cni, DROP whatsapp, DROP lieu_naissance, DROP profession, DROP representant_nom_prenoms, DROP representant_contacts, DROP representant_email, DROP representant_adresse, DROP representant_nom_pere, DROP representant_nom_mere, DROP representant_whatsapp, DROP representant_date_naissance, DROP representant_lieu_naissance, DROP representant_profession, DROP representant_date_cni, DROP representant_numero_cni, CHANGE date_naissance date_naiss DATETIME NOT NULL');
        $this->addSql('ALTER TABLE versement_proprio ADD libelle VARCHAR(255) NOT NULL, ADD numero VARCHAR(255) NOT NULL, DROP libelle_versement, DROP numero_recu');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appartement CHANGE libAppart libelle_appartement VARCHAR(255) NOT NULL, CHANGE nbrePieces nombre_pieces NUMERIC(9, 0) NOT NULL, CHANGE numEtage numero_etage INT NOT NULL, CHANGE oqp est_occupe INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contrat_location ADD date_debut DATETIME DEFAULT NULL, ADD date_fin DATETIME DEFAULT NULL, ADD date_entree DATETIME DEFAULT NULL, ADD date_prochain_versement DATETIME DEFAULT NULL, ADD deja_locataire VARCHAR(255) DEFAULT NULL, ADD caution_remise NUMERIC(9, 0) DEFAULT NULL, ADD montant_caution NUMERIC(9, 0) DEFAULT NULL, ADD montant_avance NUMERIC(9, 0) DEFAULT NULL, ADD montant_loyer NUMERIC(9, 0) DEFAULT NULL, ADD autres_infos VARCHAR(255) DEFAULT NULL, ADD montant_loyer_precedent NUMERIC(9, 0) DEFAULT NULL, ADD montant_loyer_initial NUMERIC(9, 0) DEFAULT NULL, ADD montant_loyer_actuel NUMERIC(9, 0) DEFAULT NULL, ADD montant_arriere NUMERIC(9, 0) DEFAULT NULL, ADD statut_location VARCHAR(255) DEFAULT NULL, ADD total_verse VARCHAR(255) DEFAULT NULL, DROP dateDebut, DROP dateFin, DROP mntCaution, DROP mntAvance, DROP mntLoyer, DROP autreInfos, DROP dateEntree, DROP dateProchVers, DROP mntLoyerPrec, DROP mntLoyerIni, DROP mntLoyerActu, DROP mntArriere, DROP dejaLocataire, DROP statutLoc, DROP totVerse, DROP cautionRemise, CHANGE nbMoisCaution nombre_mois_caution NUMERIC(9, 1) NOT NULL, CHANGE nbMoisAvance nombre_mois_avance NUMERIC(10, 1) DEFAULT NULL, CHANGE fraisAnex frais_annexes NUMERIC(9, 0) NOT NULL');
        $this->addSql('ALTER TABLE facture_location ADD montant_facture INT NOT NULL, ADD solde_facture_location INT NOT NULL, DROP mnt_fact, DROP solde_fact_loc, CHANGE lib_facture libelle_facture VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE locataire ADD vivez_avec VARCHAR(255) DEFAULT NULL, ADD nom_prenoms VARCHAR(255) NOT NULL, ADD lieu_naissance VARCHAR(255) NOT NULL, ADD nombre_enfants VARCHAR(255) DEFAULT NULL, ADD nombre_personnes_charge VARCHAR(255) DEFAULT NULL, ADD nom_prenom_conjointe VARCHAR(255) DEFAULT NULL, ADD profession_conjointe VARCHAR(255) DEFAULT NULL, ADD ethnie_conjointe VARCHAR(255) DEFAULT NULL, ADD contact_conjointe VARCHAR(255) DEFAULT NULL, ADD numero_piece VARCHAR(255) NOT NULL, DROP nPrenoms, DROP lieuNaiss, DROP nbEnfts, DROP nbPersChge, DROP nPConjointe, DROP profConj, DROP ethnieConj, DROP contactConj, DROP vivezAvec, DROP numpiece, CHANGE dateNaiss date_naissance DATETIME NOT NULL');
        $this->addSql('ALTER TABLE maison CHANGE libMaison libelle_maison VARCHAR(255) NOT NULL, CHANGE tFoncier titre_foncier VARCHAR(255) DEFAULT NULL, CHANGE mntCom montant_commission NUMERIC(10, 0) NOT NULL');
        $this->addSql('ALTER TABLE proprio ADD adresse VARCHAR(255) NOT NULL, ADD numero_cni VARCHAR(255) NOT NULL, ADD whatsapp VARCHAR(255) DEFAULT NULL, ADD lieu_naissance VARCHAR(255) NOT NULL, ADD profession VARCHAR(255) NOT NULL, ADD representant_nom_prenoms VARCHAR(255) DEFAULT NULL, ADD representant_contacts VARCHAR(255) DEFAULT NULL, ADD representant_email VARCHAR(255) DEFAULT NULL, ADD representant_adresse VARCHAR(255) DEFAULT NULL, ADD representant_nom_pere VARCHAR(255) DEFAULT NULL, ADD representant_nom_mere VARCHAR(255) DEFAULT NULL, ADD representant_whatsapp VARCHAR(255) DEFAULT NULL, ADD representant_date_naissance DATETIME DEFAULT NULL, ADD representant_lieu_naissance VARCHAR(255) DEFAULT NULL, ADD representant_profession VARCHAR(255) DEFAULT NULL, ADD representant_date_cni DATETIME DEFAULT NULL, ADD representant_numero_cni VARCHAR(255) DEFAULT NULL, DROP addresse, DROP num_cni, DROP whats_app, DROP lieu_naiss, DROP prefession, DROP nom_prenoms_r, DROP contacts_r, DROP email_r, DROP adresse_r, DROP nom_prere_r, DROP nom_mere_r, DROP whats_app_r, DROP date_naiss_r, DROP lieu_naiss_r, DROP profession_r, DROP date_cni_r, DROP num_cni_r, CHANGE date_naiss date_naissance DATETIME NOT NULL');
        $this->addSql('ALTER TABLE versement_proprio ADD libelle_versement VARCHAR(255) NOT NULL, ADD numero_recu VARCHAR(255) NOT NULL, DROP libelle, DROP numero');
    }
}
